### PR TITLE
Change delay metric to WPM

### PR DESCRIPTION
**Pull request by lukedev820**
Hello sorry for closing the PR im still learning how to use git effectively.

Ive resolved the merge conflict though and everything seems to work!

### CODE REVIEW

**Comment by makoteq** [comment]
No problem!

**Review by makoteq — CHANGES_REQUESTED** [review]
You need to revert these changes:
image

**Comment by lukedev820** [comment]
Sorry for all this back and forth for a simple task. I'm not sure how the dependency was added but Ive removed it none the less.

**Review by makoteq — CHANGES_REQUESTED** [review]
you need to revert this part of [package-lock.json](https://github.com/makoteq/metaxa/pull/20/files#diff-053150b640a7ce75eff69d1a22cae7f0f94ad64ce9a855db544dda0929316519)
image
U can to git manually or by using
`npm uninstall metaxa`
inside the repo

**Review by makoteq — APPROVED** [review]

**Comment by lukedev820** [comment]
By the way in the future i would use [githubs review feature](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/reviewing-changes-in-pull-requests/reviewing-proposed-changes-in-a-pull-request) instead of manually taking photos.

I had a similar back and forth with another and i was able to quickly accept the requested changes.

Anyways sorry once again for the back and forth. Thanks once again!

**Pull request merged**
