### PR TITLE
fixed output for -v flag

### PR DESCRIPTION
**Pull request by ashutoshjv661**
Creating a pull request for #27

### CODE REVIEW

**Comment by ashutoshjv661** [comment]
Please add to hacktober fest if this solves the issue ^_^

**Comment by makoteq** [comment]
Hey @ashutoshjv661 
I checked your PR, it seems that the problem was with files structure on my computer,
You still did the job right, so label is yours.
Good luck! and happy hacking 😄

**Comment by makoteq** [comment]
Hey! @ashutoshjv661 
sorry for mess
Great job! 😸

**Comment by ashutoshjv661** [comment]
Thanks for the merge ^_^ @makoteq

**Pull request merged**
