### PR TITLE
Added contributing.md

### PR DESCRIPTION
**Pull request by jsvigneshkanna**
Added new contributing md file

Please add `hacktoberfest-accepted` label

### CODE REVIEW

**Review by makoteq — CHANGES_REQUESTED** [review]
**change**

> cd color

 **with**

> 

> cd metaxa

**and i think we good to go**

**Comment by jsvigneshkanna** [comment]
@makoteq , changes done, please review the code

**Review by makoteq — CHANGES_REQUESTED** [review]
You still need to change name of the repo here
image

**Comment by jsvigneshkanna** [comment]
@makoteq 
Apologies, didnt noticed the change

Update the file as described in comment

**Review by makoteq — APPROVED** [review]

**Comment by makoteq** [comment]
Very good! , thanks for contribution 😺

**Pull request merged**
