### PR TITLE
UI Update ⚡

### PR DESCRIPTION
**Pull request by meerhamzadev**
Hello @makoteq, This PR is related to the UI update. I updated the UI of the following:

✅ Help Section
Screenshot from 2022-10-11 02-09-56

✅ Error Messages
Screenshot from 2022-10-11 02-23-26

✅ Word Display Section
Screenshot from 2022-10-11 02-10-46

Screenshot from 2022-10-11 02-10-47

### CODE REVIEW

**Review by makoteq — COMMENTED** [review]
hey, i really like your design. 😸 
But why did you use "await" in this part
image

**Comment by makoteq** [comment]
also in this section i would stick to simple "GO!"

image

Overall great job!
Im looking to merge this one soon

**Comment by meerhamzadev** [comment]
Ohhhhhh sorry, the await is a typo, and just give me a second I'll fix both.

**Comment by meerhamzadev** [comment]
Hey @makoteq, I have fixed the typos. Kindly have a look, it would be great if you add hacktoberfest-accepted label while merging this PR.

**Comment by makoteq** [comment]
Everything great, thanks for contribuition 😸

**Pull request merged**
